import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Footer from '/components/footer.js'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hima &apos;Dionysus&apos; Balde</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" key="viewport" />
        <meta
          name="description"
          content="A PWA blog and portfolio site by web developer Ibrahima Balde, Dionysus Era"
        />
        <meta name="author" content="Hima Dionysus Balde" key="author" />
        <title>Next.js Dionysus Era Dev</title>
        <meta name="keywords" content="Next.js, React, Portfolio, Md, JSX" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
        <link href="/img/favicon-16x16.png" rel="icon" type="image/png" sizes="16x16" />
        <link href="/img/favicon-32x32.png" rel="icon" type="image/png" sizes="32x32" />
        <link rel="apple-touch-icon" href="/apple-icon.png"></link>
        <meta name="theme-color" content="#317EFB" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Dionysus Era Dev</h1>

        <p className={styles.description}>JAMstack &rarr;Fullstack&rarr;React Apps</p>

        <div className={styles.grid}>
          <a href="https://github.com/bahim22/last-nxt-ded" className={styles.card}>
            <h2>My Repos &rarr;</h2>
            <p>Several Projects and React/Next boilerplates</p>
          </a>
          <a href="/posts" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>In Depth documentation of Next.js App Building</p>
          </a>
          <div className={styles.wrapper}>
            {/*<div className={styles.card}>*/}
            {/*</div>*/}
            <span className={styles.logo}>
              <Image
                src="/img/android-chrome-512x512.png"
                alt="Dionysus Logo"
                width={530}
                height={500}
              />
            </span>
          </div>
        </div>
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  )
}
