import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hima &apos;Dionysus&apos; Balde</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Dionysus Era Dev</h1>

        <p className={styles.description}>JAMstack &rarr;Fullstack&rarr;React Apps</p>

        <div className={styles.grid}>
          <a href="https://github.com/bahim22/last-nxt-ded" className={styles.card}>
            <h2>My Repos &rarr;</h2>
            <p>Several Projects and React/Next boilerplates</p>
          </a>
          <a href="/posts" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>In Depth documentation of Next.js App Building</p>
          </a>
          <div className={styles.wrapper}>
            {/*<div className={styles.card}>*/}
            <span className={styles.logo}>
              <Image
                src="/img/android-chrome-512x512.png"
                alt="Dionysus Logo"
                width={500}
                height={350}
              />
            </span>
            {/*</div>*/}
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://github.com/bahim22" target="_blank" rel="noopener noreferrer">
          Gullo by{' '}
          <span className={styles.logo}>
            <Image src="/logo.svg" alt="Dionysus Logo" width={125} height={50} />
          </span>
        </a>
      </footer>
    </div>
  )
}
